#!/usr/bin/env bash
# Install Nginx web server
sudo apt update
sudo apt install nginx

# Create a new server block configuration file for your domain
sudo nano /etc/nginx/sites-available/solamsalu.tech

# Add the redirection configuration
echo "server {
    listen 80;
    listen [::]:80;

    server_name example.com;

    location /redirect_me {
        return 301 https://solamsalu.tech/www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # other server configurations
}" | sudo tee /etc/nginx/sites-available/solamsalu.tech > /dev/null

# Create a symbolic link to enable the new server block configuration
sudo ln -s /etc/nginx/sites-available/solamsalu.tech /etc/nginx/sites-enabled/

# Verify the syntax of the Nginx configuration files
sudo nginx -t

# If the syntax is OK, reload Nginx to apply the changes
sudo systemctl reload nginx
