#!/usr/bin/env bash                                                                                                   
# Uses ssh to connect to server with private key and user given                                                       
ssh ubuntu@54.87.237.1 -i ~/.ssh/school